/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

typedef struct namenode *namelist;

struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;

struct readdir_res {
	int errno;
	union {
		namelist list;
	} readdir_res_u;
};
typedef struct readdir_res readdir_res;

#define DIRPROG  0x20000076
#define DIRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READDIR 1
extern  readdir_res * readdir_1(nametype *, CLIENT *);
extern  readdir_res * readdir_1_svc(nametype *, struct svc_req *);
extern int dirprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READDIR 1
extern  readdir_res * readdir_1();
extern  readdir_res * readdir_1_svc();
extern int dirprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_namenode (XDR *, namenode*);
extern  bool_t xdr_readdir_res (XDR *, readdir_res*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_namenode ();
extern bool_t xdr_readdir_res ();

#endif /* K&R C */


//===================
typedef struct file_open_request {
    char* filename;
    char* mode;
}file_open_request;

typedef struct file_open_result {
	int errno;
	union {
		void* file_ptr;
	} file_open_result_u;
}file_open_result;
#define FILEPROG 0x20000077
#define FILEVERS 1


#if defined(__STDC__) || defined(__cplusplus)
#define OPENFILE 1
extern  file_open_result * openfile_1(char**, CLIENT *);
extern  file_open_result * openfile_1_svc(char **, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READDIR 1
extern  file_open_result * openfile_1();
extern  file_open_result * openfile_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, char**);
extern  bool_t xdr_openrequest (XDR *, file_open_request*);
extern  bool_t xdr_file_open_result (XDR *, file_open_result*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_openrequest ();
extern bool_t xdr_file_open_result ();

#endif /* K&R C */



#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
