/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <stdio.h>

void
dirprog_1(char *host, char *dir)
{
	CLIENT *clnt;
	readdir_res  *result_1;
	nametype  readdir_1_arg;
    namelist nl;
    
    printf("%s %s\n", host, dir);
#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIRVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = readdir_1(&dir, clnt);
	if (result_1 == (readdir_res *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    
    for(nl = result_1->readdir_res_u.list;nl!=NULL;nl = nl->next)
        printf("%s\n", nl->name);
        
    xdr_free(xdr_readdir_res, result_1);
        
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    char *dir;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    dir = argv[2];
	dirprog_1 (host, dir);
exit (0);
}
