/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <dirent.h>

//extern int errno;
extern void *malloc(unsigned int num_bytes);
extern char *strdup();

readdir_res *
readdir_1_svc(nametype *argp, struct svc_req *rqstp)
{

	static readdir_res  res;
#if 1
    DIR *dirp;
    struct dirent *d;
    namelist* nlp;
    namelist nl;
    
    printf("%s\n", *argp);
    
    dirp = opendir(*argp);
    if(dirp == (DIR*) NULL){
        res.errno = 1;
        return &res;
    }
    
    xdr_free(xdr_readdir_res, &res);
    
	nlp = &res.readdir_res_u.list;
	while (d = readdir(dirp)) {
		nl = *nlp = (namenode *)malloc(sizeof(namenode));
		if (nl == (namenode *) NULL) {
			res.errno = 2;
			closedir(dirp);
			return(&res);
		}
		nl->name = strdup(d->d_name);
		nlp = &nl->next;
	}
	*nlp = (namelist)NULL;
	/* Return the result */
	res.errno = 0;
	closedir(dirp);        
    
	/*
	 * insert server code here
	 */
#endif
	return &res;
}
