/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filemode (XDR *xdrs, filemode *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_open_request (XDR *xdrs, file_open_request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_filemode (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_close_request (XDR *xdrs, file_close_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->file_ptr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_open_request_res (XDR *xdrs, file_open_request_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_int (xdrs, &objp->file_open_request_res_u.file_ptr))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_file_close_request_res (XDR *xdrs, file_close_request_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_int (xdrs, &objp->file_close_request_res_u.ret))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
