/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "file.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

file_open_request_res *
openfile_1(file_open_request *argp, CLIENT *clnt)
{
	static file_open_request_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OPENFILE,
		(xdrproc_t) xdr_file_open_request, (caddr_t) argp,
		(xdrproc_t) xdr_file_open_request_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

file_close_request_res *
closefile_1(file_close_request *argp, CLIENT *clnt)
{
	static file_close_request_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CLOSEFILE,
		(xdrproc_t) xdr_file_close_request, (caddr_t) argp,
		(xdrproc_t) xdr_file_close_request_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
