/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *filename;

typedef char *filemode;

struct file_open_request {
	filename name;
	filemode mode;
};
typedef struct file_open_request file_open_request;

struct file_close_request {
	int file_ptr;
};
typedef struct file_close_request file_close_request;



struct file_open_request_res {
	int errno;
	union {
		int file_ptr;
	} file_open_request_res_u;
};
typedef struct file_open_request_res file_open_request_res;

struct file_close_request_res {
	int errno;
	union {
		int ret;
	} file_close_request_res_u;
};
typedef struct file_close_request_res file_close_request_res;

#define FILEPROG 0x20000077
#define DIRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPENFILE 1
extern  file_open_request_res * openfile_1(file_open_request *, CLIENT *);
extern  file_open_request_res * openfile_1_svc(file_open_request *, struct svc_req *);
#define CLOSEFILE 2
extern  file_close_request_res * closefile_1(file_close_request *, CLIENT *);
extern  file_close_request_res * closefile_1_svc(file_close_request *, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPENFILE 1
extern  file_open_request_res * openfile_1();
extern  file_open_request_res * openfile_1_svc();
#define CLOSEFILE 2
extern  file_close_request_res * closefile_1();
extern  file_close_request_res * closefile_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_filemode (XDR *, filemode*);
extern  bool_t xdr_file_open_request (XDR *, file_open_request*);
extern  bool_t xdr_file_close_request (XDR *, file_close_request*);
extern  bool_t xdr_file_open_request (XDR *, file_open_request*);
extern  bool_t xdr_file_close_request (XDR *, file_close_request*);
extern  bool_t xdr_file_open_request_res (XDR *, file_open_request_res*);
extern  bool_t xdr_file_close_request_res (XDR *, file_close_request_res*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_filemode ();
extern bool_t xdr_file_open_request ();
extern bool_t xdr_file_close_request ();
extern bool_t xdr_file_open_request ();
extern bool_t xdr_file_close_request ();
extern bool_t xdr_file_open_request_res ();
extern bool_t xdr_file_close_request_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
