/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"

file_open_request_res *
openfile_1_svc(file_open_request *argp, struct svc_req *rqstp)
{
	static file_open_request_res  result;

    printf("%s %s\n", argp->name, argp->mode);
    //result.errno = 0xFF;
    
    FILE* f = fopen(argp->name, argp->mode);
    if(f != NULL)
    {
        result.file_open_request_res_u.file_ptr = (int)f;
        printf("file open %s success, file handle: %x\n", argp->name, result.file_open_request_res_u.file_ptr);
        fputs("xxx", f);
    }
    else
    {
        result.file_open_request_res_u.file_ptr = NULL;
        printf("file open %s failed\n", argp->name);
    }
    
	return &result;
}


file_close_request_res *
closefile_1_svc(file_close_request *argp, struct svc_req *rqstp)
{
	static file_close_request_res  result;

    printf("closing file handle %x\n", argp->file_ptr);
    
    FILE* f = fclose((FILE*)argp->file_ptr);
    result.errno = 0;
    result.file_close_request_res_u.ret = 2;

	return &result;
}